### PR TITLE
Readme fixes and an addition

### PR DESCRIPTION
**Pull request by lolmaus**
Rewritten some paragraphs for clarity, removed a duplicate line.

Added info how to trigger **eq.js** when you don't have access to added nodes.

### CODE REVIEW

**Comment by lolmaus** [comment]
Updated.

**Comment by lolmaus** [comment]
I started the PR to write that very section 'cause i wasted good half an hour trying to figure that out.

PS GitHub does not send texts of edited messages.

**Comment by Snugug** [comment]
Dispatching events is outside of the scope of normal use for most users and, especially for the `resize` event which may have many things associated with it, is far from a best practice that one should be using. It's not something I'm going to recommend.

Instead, documenting that `eqjs.refreshNodes()` refreshes the list of nodes available would be preferable. That can then be combined with the already documented `eqjs.query()` to actually query all nodes, including new ones. That's all [the `resize` event is doing anyway](https://github.com/Snugug/eq.js/blob/1.x.x/build/eq.js#L257-L258)

**Comment by lolmaus** [comment]
Awesome, i will update the paragraph with `eqjs.refreshNodes()` instead of the event.

Do you demand a squash?

**Comment by Snugug** [comment]
Nope, whatever you'd like

**Comment by lolmaus** [comment]
Done. :bowtie:

**Comment by lolmaus** [comment]
Done. Squashed my commits into one. :angel:

**Pull request merged**
