### PR TITLE
Attributes

### LINKED ISSUE #17: Add multiple values to data-eq-state when more than one is true
For example, when an element has a small, medium and large state and medium is true, small should also be added to data-eq-state as it is also true.

### PR DESCRIPTION
**Pull request by Snugug**
Resolves #17

### CODE REVIEW

**Comment by Snugug** [comment]
This is backwards compatible as long as you are not relying on the content of `data-eq-state` outside of the provides Sass mixin, and will need to be re-compiled. Should this be considered a breaking change, or a point release with its changes identified?

**Comment by Snugug** [comment]
I give everyone 10 days to comment; if no clear consensus has been decided by then, I'm just going to merge it in.

**Comment by heyMP** [comment]
I love it, works great!

For some reason the eq mixin is throwing an error in sass compilation though.  Not sure if it has anything to do with the update; might just be my setup.  I'm using compass 1.0.3 and sass 3.3.0

`error sass/styles.scss (Line 42 of bower_components/eq.js/sass/_eq.scss: Invalid CSS after "...[data-eq-state=": expected identifier or string, was "$"#{$state}"] {")`

**Comment by Snugug** [comment]
@heyMP There was a syntax error that I've just fixed, but this stuff will only work with Sass 3.4 or greater.

**Pull request merged**
