### PR TITLE
fixes #65

### LINKED ISSUE #65: Calculating the width of objects
This is problem with simultaneous changeover of states in the set of elements during browser resize.
When rounding values offsetWidth on certain width some elements go to the next state, while some are not.

A living example:
http://jsfiddle.net/LostSenSS/15j004L6/

Screenshot:
https://www.dropbox.com/s/ilh7h2skhgpaz2q/15j004L6.png

Possible solution. If instead of      

``` javascript
widths.push(nodes[i].offsetWidth);
```

use

``` javascript
widths.push(nodes[i].getBoundingClientRect().width);
```

then the problem disappears.

### PR DESCRIPTION
**Pull request by FezVrasta**
fixes #65

### CODE REVIEW

**Comment by jonscottclark** [comment]
This breaks IE8, as its getBoundingClientRect() object does not return width and height properties. eq.js supports IE8 with the included polyfills, so I think this won't be merged unless a fallback to this method is added.

Couldn't find an easy drop-in polyfill, but here's an implementation that should work in older browsers: https://github.com/zeroclipboard/zeroclipboard/blob/be4573579f9dbccad4280bd06e2e72c896fa5c66/ZeroClipboard.js#L124-L155

**Comment by Snugug** [comment]
As @jonscottclark said, as I'm trying to keep IE8 compatibility, can't use `getBoundingClientRect` without a suitable polyfill available (and pulled in during the build process)

**Comment by FezVrasta** [comment]
What about https://github.com/inexorabletash/polyfill/blob/master/cssom.js ?

**Comment by vampolo** [comment]
@FezVrasta your suggested polyfill is based on [Object.defineProperties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties) which seem to be supported from IE9+. Thus i dunno if the comment in the suggested snippet is correct.

As a solution to this, there is a polyfill for _Object.defineProperties_ on the mozilla MDN.

**Comment by jonscottclark** [comment]
The polyfill I linked seems to do what `getBoundingClientRect` does within the browser, but man.. it's really long.

**Comment by vampolo** [comment]
Why don't just do:

```
var rect = el.getBoundingClientRect();
var width = rect.width;
if (width === undefined) {
    width = rect.right - rect.left;
}
```

Or something similar ?

**Comment by FezVrasta** [comment]
I think it could work... well, obviously we'll still have the the problem fixed by this PR on IE8, but it's still an improvement.

**Comment by FezVrasta** [comment]
closing in favor of #71

**Pull request closed without merging**
