### PR TITLE
add Bower package version & devDependency currency badges to README

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by Snugug** [comment]
Happy to add them, although I'd prefer them placed next to the name instead of under it. If you can do that, I'll merge this in!

**Comment by cvrebert** [comment]
Sure! Different projects seem to go different ways on where badges go, happy to tweak this.

**Comment by cvrebert** [comment]
Done.

**Comment by Snugug** [comment]
Great, thanks!

**Pull request merged**
