### PR TITLE
Comment updates

### PR DESCRIPTION
**Pull request by rupl**
This branch switches the comments to regular JS comment blocks, and adds a license block at the top with uglify-friendly comment syntax so it's retained when put through a minifier.

### CODE REVIEW

**Comment by rupl** [comment]
Also if we resolve #10 then I will update this PR with all the necessary changes to complete the work.

**Comment by Snugug** [comment]
Also, don't build the minified version; I'll do that before the release.

**Comment by Snugug** [comment]
For the license block, I'd prefer not to handle that manually and instead have it be part of the Build task. See [Grunt Uglify's banner](https://github.com/gruntjs/grunt-contrib-uglify#banner)

**Comment by Snugug** [comment]
Can you re-roll this clean? Sorry it looks like your updates got lost because GitHub doesn't send notifications when new commits are added to a PR

**Comment by rupl** [comment]
I'm not quite sure what was lost, but I've merged in the latest 1.x.x and the diff seems to be what I'm expecting to see.

**Pull request merged**
